/*
 *
 * String matching with k mismatches
 *
 * Bioinformatics project
 *
 * Authors:
 *  Domagoj Korman
 *  David Romic
 *  Vilim Stubican
 *
 *
 */

#include <sstream>
#include <iostream>
#include <vector>
#include <fstream>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <math.h>
#include <map>
#include <set>
#include <unordered_map>


using namespace std;

char *program_name;

void usage() {
    cerr << "Usage: " << program_name << "[OPTION]..." << endl;
    cerr << "This program reads in a corpus and stores it in a ";
    cerr << "suffixarray.  It then returns the number of occurrences ";
    cerr << "of char*s in the corpus." << endl;
    cerr << "  -h, --help        ";
    cerr << "Show this help and exit" << endl;
    cerr << "  -f, --file FILE   ";
    cerr << "Filename of the corpus to be read" << endl;
    cerr << "  -s, --server PORT ";
    cerr << "Turn server mode on, listening on the port" << endl;
    exit(0);
}

class Mismatcher {
protected:
    char *text;
    char *pattern;
    int textLength;
    int patternLength;
    int k;
    int *subsetPositions;
    int subsetCount;

    Mismatcher(char *text, int textLength, char *pattern, int patternLength, int kVal);

    void defineSubsets(int every);

    // This is abstract method, this needs to be implemented
    virtual int updateMismatches(int positionInText) = 0;

    virtual void init() = 0;

public:
    int *findMismatches();
};

Mismatcher::Mismatcher(char *t, int tLength, char *p, int pLength, int kVal) {
    text = t;
    textLength = tLength;
    pattern = p;
    patternLength = pLength;
    k = kVal;
}

void Mismatcher::defineSubsets(int every) {
    subsetCount = 0;
    for (int i = 0; i < textLength; i += every) {
        subsetCount++;
    }

    subsetPositions = new int[subsetCount];
    for (int c = 0; c < subsetCount; c++) subsetPositions[c] = 0;

    int counter = 0;
    for (int i = 0; i < textLength; i += every) {
        subsetPositions[counter++] = i;
    }
}

int *Mismatcher::findMismatches() {
    int *mismatches = new int[textLength];
    // non checked mismatches will have -1
    for (int c = 0; c < textLength; c++) mismatches[c] = -1;

    defineSubsets(1);

    int i = 0;

    while (i < textLength) {
        int l = 0;
        int j = 0;

        while (j + l < patternLength) {
            int tmpL = 0;
            int tmpI = i;
            int tmpJ = j;
            while (tmpJ < patternLength && text[tmpI++] == pattern[tmpJ++]) {
                tmpL++;
            }

            if (tmpL > l) {
                l = tmpL;
            }
            j++;
        }

        for (int sCounter = 0; sCounter < subsetCount; sCounter++) {
            // position unset is done with -1
            if (subsetPositions[sCounter] < 0) {
                continue;
            }

            int pos = subsetPositions[sCounter];
            if (pos <= i && i < pos + patternLength) {
                int mismatchAmount = updateMismatches(pos);
                if (mismatchAmount > k) {
                    subsetPositions[sCounter] = -1;
                }

                if (mismatchAmount > mismatches[pos]) {
                    mismatches[pos] = mismatchAmount;
                }
            }

        }

        if (l > 0) {
            i += l;
        } else {
            i += 1;
        }
    }

    return mismatches;
}


/**
 * Derived class
 */
class NaiveMismatcher : public Mismatcher {
protected:
    int updateMismatches(int positionInText);

    void init();

public:
    NaiveMismatcher(char *text, int textLength, char *pattern, int patternLength, int kVal);
};

NaiveMismatcher::NaiveMismatcher(char *text, int textLength, char *pattern, int patternLength, int kVal) :
        Mismatcher(text, textLength, pattern, patternLength, kVal) {
    init();
};

void NaiveMismatcher::init() {
    // some empty space initialization
    cout << "Naive mismatcher init" << endl;
}

int NaiveMismatcher::updateMismatches(int positionInText) {
    int mismatches = 0;
    for (int i = 0; i < patternLength; i++) {
        if (text[positionInText + i] != pattern[i]) {
            mismatches++;
        }
//        if (mismatches > k) {
//            return mismatches;
//        }
    }

    return mismatches;
}

class KangarooMismatcher : public Mismatcher {

protected:
    char** suffixArray;
    int* isa;
    int* lcp;

    int updateMismatches(int positionInText);

    void init();

    void createLCP();

    int RMQ(int index1, int index2);

public:
    KangarooMismatcher(char* sa[], int isa[], char *text, int textLength, char *pattern, int patternLength, int kVal);
};

KangarooMismatcher::KangarooMismatcher(char* sa[], int isa[], char *text, int textLength, char *pattern, int patternLength,
                                       int kVal)
        : Mismatcher(text, textLength, pattern, patternLength, kVal) {
    this->suffixArray = sa;
    this->isa = isa;
    init();
}

void KangarooMismatcher::init() {
    cout << "\nInit Kangaroo mismatcher\n";
    createLCP();
}

void KangarooMismatcher::createLCP() {
    lcp = new int[textLength + patternLength + 1];
    for (int i = 0; i < textLength + patternLength; ++i) {

        //Calculate LCP between string and string i + 1
        char* text1 = suffixArray[i];
        char* text2 = suffixArray[i + 1];
        int text1Length = strlen(text1);
        int text2Length = strlen(text2);
        int lcpValue = 0;
        int j = 0;
        while (j < text1Length && j < text2Length
               && text1[j] == text2[j]) {
            lcpValue++;
            j++;
        }
        lcp[i] = lcpValue;
    }
    lcp[textLength + patternLength] = 0;
}

int KangarooMismatcher::RMQ(int index1, int index2) {
    int lcpIndex1 = isa[index1];
    int lcpIndex2 = isa[index2];
    int rmq = 100000;
    if (lcpIndex1 > lcpIndex2) {
        for (int i = lcpIndex2; i < lcpIndex1; ++i) {
            if (lcp[i] < rmq) {
                rmq = lcp[i];
                if (rmq == 0) return 0;
            }
        }
        return rmq;
    }
    if (lcpIndex2 > lcpIndex1) {
        for (int i = lcpIndex1; i < lcpIndex2; ++i) {
            if (lcp[i] < rmq) {
                rmq = lcp[i];
                if (rmq == 0) return 0;
            }
        }
        return rmq;
    }
    return -2000;
}

int KangarooMismatcher::updateMismatches(int positionInText) {
    if (positionInText <= textLength - patternLength) {
        int mismatches = 0;
        int l = 0;

        while (true) {
            l += RMQ(positionInText + l, textLength + l + 1) + 1;
            if (l > patternLength) {
                return mismatches;
            }
            if (l == patternLength) {
                return mismatches + 1;
            }
            mismatches++;
            if (mismatches > k) {
                return mismatches;
            }
        }
    } else {
        return k + 1;
    }
}

int main(void) {

//    char* text = "GACTTATGCCTGATCGCTGTCAGGTCATACGCTTCATTTATGACTTGGCATAACCGGTTTTCTGATGCCACTCGAAGGCACCGTGTTTAACCCTATTCGCGAGGAAATGAGGAACTTCGCCACACCGTGATAACGTTTCTTTATCTTTACCCTGCATCACCCAAGGCTGGCTCGATAATCGAGTTTTGGCGCATCTTCGCATCGGCGTCGTGACAGGGCATCATGCCTACGCTTAGTTAAAATTTGGCTAATGTAGAAATGTTGGCAAGAGAACCGGAAGAGGCGCTTATTACCATCTAAGGATACGTTATAGAAACTTCTCGGTGGATTCATCCTTACGAACAGGGTGCTCGAAGTCGCCCTTCTTATTTCATCTCCTCGAGCACTGGCGATGTGTTTCTCACCTGCTCCGGCTTATTGAACTCCAGCACCGGTTCTGGGGCTGCTCGTTAAAGCCGTTGTTTGCTGGCAAACGGCAAGACCGGTTCCAGGCCTAAAGTTTCCAGTTGGATCACCAGCCTTCAGCGCTGGCGTATCCGCTCGAGCACTTCATTAAGAGGCTTTGCAGTTTCGCGGCATAGTCCGCGGTGCCATCCGTGCCTGGAGCGGCTGTTCGTTCGAGGTCTAATCCCCTTCGCTTTCTTGAAGCGTCTTTGTTGTAATAGAAACGCGTAGGGTGGTCGAGTGGCTGGAGAGTAAGTGGCCCGTTTGCTGTCGGAGTAGGTCAACCTGAAACCGTCGGCACAAACTGCGACTCATCGAACTGAATCCCTTGCCTCTTTAAACACGTCATATACACCGGTTTTAATGGCCTCGACGCCATCATGGTGGCGGTGCCAATTGCCAACCTGCGCAAAATAGCCGGCGCGTGTTGCCGGTACGAAAAATGCGGCAATCCCGGCGCTTAGCAAATTCGCTGTTATGCTGTGGTCTAAATCGTACAATTTGTAATCCGGGTTTTCGGCGTTAAAACGTTGGGCCAGAGAATATCCACCTCTTTACCCAGTTTCCCCTTCCATAGAATTCTCCAGAACCGAATACTTTATGTCACTGCCTGTGCATTCCCCATTGGACGCCAGTCCGATAGCCAGTGCTGAAGCTGTATAATGTAAACGGTTTCATCGTTTTATCTCTCTTGTTGTACCGAATTGCGCGAATTGTCTCCGCGTTTAGCCGCGGGGTAACATGACATGCTCGAACTTACAGAAAAATAACTTTGTTACATTTGTAAGATAGTAAGGTGTCAGAAAGATGACAATAGGCGGTGACGGCGTGGGTGAGGGAAAATGGAGATGGCAACCATGAAAATAGCGAACCATGAATCAAACTCTACATAATTGCTCATCGTTTCATGCCGGATGCGCTAGTACAACGCCTTAAGGCCTGCTATACAAGTACGTGCAAATTCAACATACTTGTCGCCACTCACCCAGTAGGCCTGATAAGCGCAGCGCGCATCAGGCAATTTACATTTGTCATGTCTCAAAAGGAAGTTTTACTCCCTATCAAATCAACGTGTTATTACCCGCTAAATACGCACTTCTCACTAGATTCATTTCGCCATGGATAAGAATAGCATCAGTATCGGAAACCCACTACATTAGGACTTTTCCTCAGCACGATATCGCGATCGCCAGCTTTAGCCGCTCTGCGTTTTGTATGCTCGACGAGACAGAGTCATGCCCTGGTATCGCTCGCAGCTGCTGAGTGGTGTCGAATTGCTGGATGATAATCGGCGCAAGACCGAGCGATGGCTCAGACCCAAGGGCAGTAGCAAACCGCGGGTTAGCGCTCAGGCGCAACGACCAATCGCCAGCATCTGCTGTTCAAGCCGACATGGTGCCGCCCGCTGAATACCGGCGCTCATGCGGCAGACGTGGAAAACAGGCTCATAACCCCACTTATGCGCTCCCTGGAACTGGTCGCGTTCAGCAAAACCCCAAGCCAGGTTCTCTTCCACCGTCATCCGCGAGAAAGGCGCGACAATTCGCTCCACCGCTTCGCGCATGATTTCGCTGTCTGCCAGTCGGTAATGTCTTTATCATCAACAAGAACTTCACGCTGGTGGCACAAATCGTAAGCCAGAAGCTCATGTGCCAGCAAGTGGTTTTCCCCGCGGTTTCGCGCCAATCATGTGGTAAATCGCCCTGATTGATATGCAGGCTCACCTCATTCACAGCGCTCCGATTTGCATGTAGTGGGCGCTGATTTGTCAAAGGACAACATGACTTTTCCATCTTATGCCTCACTAAATAGGGATCGGATTTCACGGGTTATTACGAGGATCACGCTCCGTGTACTCCGTTTGCATAGCGGCGTCCCCTGATTGACCACGTATAAATTCGGTCGGAGAACTTCCCATCACCATGGTTTCATATCGGTGCCAGATCAACAAGATAGTGGTGTTGTATGATTGCGGCATATTTCGGCAATCAGTAGGCCATCGAGCGTTCTCGTGTCTCTTCGGGTTAAGACTTGCCACGCAGGTTCGGTCGAGGCATTAAATCTCCATCTGCGTCACCATGCAGCGGGCACTCACATGAAATGGGGGCCTGTACATTACCAGCGGTACTCGCTGACGGTTGAGGTCCATCCAGCAAACCAATGCGCTCAAGCCAGGTCCCGCGGCCGCGGTCCCGAGCGCTTCGCTGCGGCGCGGGAAAGGAATAACCGTTTGTTCCAAACAGGCCAGAGAAACAGCCCGGTTTTCAGTTGCTGATGCTGCGCCACCAGCAGGTTTGCCAATTACCGTCATTTTTCACGAGTAAAGCACATGCTGAGAAGGTGCGCACCACGCGATGCGGGCAATTTGCTGCCCGGTAAAACCTTCCAGGTGTGCTGCAAGCGCAGTAAAATGGTGCTCATTGAGTTTGTAGAATCCGGTCAGACAGTCAAAATGGCTGTGGTTTTGCCCCTGGAGCCACATGTTGGCCGATCACGGAAAGCATCCCTCCTGCGGGTACAGTTCAAGATTGACGACATGTTGTTCAAGCCAGCAGGCGCCAAGAAGCGCATCAGGCCGTTTAACAGATAATAATGGCTATGACTCATGCTCGCCTGCTCTCCTTTCGCTTGCGCCGTTTGCCATTTGAGCTTGCGGCGCGTCATGGGCAGCAATCCCTGCGACGCCAGAAATTGATGATGATAGGCACCATCAAACCACCGAGCATTAACACTTGGCCTGTATTCGTTGAAATCACGCATCAAGCGCGACACCACCAGCAAACTTGCCGCCAGAATCAAGCGCAAATGCGAGCGATAATAGCCGAGCACCACTATCGCCGCACACAAACCGCCGAATGTTGTAAAACAGGTGAAGGATTCCGGGCTGACAAAGCCCTGAAGCGCCGCAAACAGCGTTTCCGCAAACCGGCAACGAGGCTATTAAAGGCAAGTCAGCTTGATACGACGCGGGCTGCACCCCAGCGAAACGGCAGGCGATTCCGACTTCGCGGCTATTCGCACCCAACCAGCGCGGGAGGTTGAGCATATCAATAGAGGCCTTAACAAGCTCGAGGGACCGAGGGAAAGTACGATCGCGTACTGTTATTAATGCGCAAACAGCAGCCACGGAAACTTGGCTGACATGTTAAATCGAGCGCTTCGAGGCCTGCCATCAATCATGGCAACTGCGGAAATGTCATGTTTACGCGTACTGCTCGTAATTTACATTTCGAGCATCCTGTCCAAATTACATCCGCTGTCACGAGGTGGAGGATAAAATCGCTTACGGAGCAGCACCAAGAAAGACCAATATCCCAGCAGGAGACAGGGTTACATTAATCGAGCGAGTGGCAAGCAGGTCAGGCACCAGCCGTAATGATTACGCAGGTGTGAACCACTAAACGATCGACTCCAATCTCACAGCACCAGCAGGCGCGACTATAGAACAGTTTCGAGCGCCAAGGGAGCTGGAGGATAATGTACAGAAGTTAAACTTCGCCTGGAAAACGACGCTTTGCCACCCTCGTGAAAATCAGCTCGCAAAGCTGACAGACAGAAGGCCTGAGGGATAAATGTTGACTTCAACGCCTTGAAATACATCCGAACCCAGGGTGGCACAATGTATTTCGGTCGCGAGCCCATTTTAATCCATTTCTGGAAAGGCCCATTTAAATCCCGCCCAGCACAAAGGCAAAAGAGCCCTAATGTTACATCACTAGCCACTTAAGCCTGCCACTGGCCCAGCCATGTCGCTCGCGGTTGGTGCCTAATGGGCGACCCAAGTTACCGCTAGGGCACCCACCAGCATGATACCAACCAGGGGCAGCGATTGAGACTTACATCGTTGTCATATTTCTATACCATGCCGATAGGCAAGAAATACCAGGTTTCGCGACTCCGCAACATCCCAGAATCAGGGCGAATCAGCCAATTGACTTCGCTGCTCCGGGGCGAAGGCCCTCCAATCCCCAATGTACAGCCGCGGTAAGGTACCTCATCCCGGAGTATAAATGCCGATGTGTACCCATAAGGGAAACCGGTCCGTATAGAATAATAGCGAATGGCGTACCTGTACTAAGTGCCTGAAGCCATCACAAAGAGTACTCAATCACCCGGGTCCCCGGTCAATGTCTCGTACCGACCGAGCCATTTTCAAATTCTTCGCAGGCGCACAGAGGACTGGAGATGCGGGAATAGCGAATCCCAAATCGTTGCCAGCATCGAGGAAAGGTAACAATCGCAGGTCACGACTTCCGCATGGTAATACAGAGGCAGAGAAGTTTTCGCTATGCCTCCACCATGACCGTCGACCCGAAGGACATTTGGAGCATCTTCAACCTGCCTGAACCTCGTACTATTGTTGCGAGGAAGGTGAGCCGATTGCAGAGATGGAGGTTAGCATCAGGCGCTTGAGTTACGCACCGGGCGGTACATCCACCCGTTCGATACTCCAGCCGGTAGGCGCTGGCAATGACGATTGCGCCGACGAATCCCGCAGCTACCAGCAGCCAGCCGGTATCAATTGCCCATCATCATCAGCGCGGCGATGAGCATAAATGAGACTGTAGCTGCCAATCATATAAAACCTCACGTGGGCGAAGTTGATTAATGCCGATAATGCGAGTGTAAATCGCTCTGTAGCCGATGGCTATCAGCGCGTAATATGCCCAGCGTGACGCTTGTTACAACATCTGCTGCAAGAAATACAAAACTGCTCAGACATAAGGTGATTTCTATAAAACCCGCGAATCTGATTTACGGGCGGTGGAGACCTTAATATTGCTGCCTGTGGATGAACCCTTCGGCGTGCCACTGGAAAGACACCAAATCAAAATCCCTTAAGTACCGCCTTTTCATCCCAGTTTCAGCGGCCCAATCGACATGTTTGCACCGTCAGCTTTAATCTTCACCAGCGCCAGCGGCTCATCGCTGCCGGTAAGCTCAAGGGCATTACCTCAGAGATTGCACCGCTGCGTGAGGTGATCAAGAAAGAGCCGACGGCATCCGATTTCTCTTGTCTGCTTTCAGCGCATCAAAGCTCCTTCGATATTGCCATTACGGGTCATAGCGTTTTGGCATAGTGACCAACATTCCATTTCGGCGATAGCAGCATACCGGCAATGTTCAGCGGTACATTCCGGCCCCATAAAACTGGGGTTTGAGGCCAACGATGAAGCATCTGCCCCATTTCCGGGTAAACTCAGGCCTTAAACGAAGTTAAGTGTTTCTTTTCAGGGCGTAAGCAGTAAGGCGCGGAGAAATCTTTTCTCCCCGGCGGTAATACCGTCGAAGAAGAAAGGACGTTGGCGTTAGCCGTGCCATCAAGTCTTAAGCGAACACGCGCCATACGTGCCATACTGTTGTTTGGTGTAGAATGATGGCCGCGATGCTGGGGGTTCCACCGTCTCAAGAATGTATTTTGCCGCTTGTTGGCCCCTGGGAAGAGTCCAGCCCGGCAAGTACTGGCATAATGTTGATACACGGTGTTGGGTCAGCTCCGGGTTGGTCGCACTCCCAGGCGATCATCAGAATACCTTCGTGTCTTCATAGATATCTGGACGCAGGCTGGGTAGAAGAAGAAAACACAGATGACCAATTAACTGTCATATTAATTCATATTAACGATTGTTGTAGAAGCTCGAAACGGCTTGTTTCGGGTCGCGCATGCGTGACTATTCCAACGTGCCCAAACCAGTTTGACGCCTCTTAAATTCCCCTTTGGCATCTTGATGTCTTTAATTGCCTGAAGGCCTGTTAAATTCCATATCGCCCCACTGGGCAATCGGTGAGCGGACATCGCGCCGACAAACCCTGCGACTTTGTCATGGTCAGCCATAGCGGTGTGAAAATTGCCAGTCACAAATCGTATCCCTGCGATGATAGTTTTCGCATTTCCGTTTCATAGTCAAATCCCATTCGTGATGTTGGTTGTGTTTTATGTTAACAAATCAGACTGTTCTTTATACTGCACTGTTTTGCCTGTCTGATCTTAAGGGGTTAGCGCAGTATTTTGGTCAATAGCGATTAAACCCTATTTTCATAGTCGATTAAGAAACAGATAATATTCTGAAGTCTTACAGAGACTAAACAGAAAATTGCCTTTGTCAGCATAAAATACAACGGCACAAATGAGAAATAATTCACTATCATTCAGGGGATCATGATCTGGACATTTTCATCTCTTCTAATGTTTTAATTTGTAATTATTGCTGTTAAAATTAATCACCTGCCAAAGAAATAAAAGAGAAAGCCTCCGATTAAATTATTTCGCTACACTGGTTTCACTTTGTGATTACACGGGTTACCCATGAAGCTGACCATCATTCGATTGGCGAAAATTGGTAATACAGACCGGGAATAAGGTGCATTAGCAAAGATCACCTGGCCGATGATTCCCCTTCCTCGTTTACAGGTTGACGATAACCACCGTATCTACGCCGCGCGTTTTAACGAGCTTGCGTCGCTAGCCATGCAGGTTGTCCGGGTAACCTTACAAGCGGCACCGAGGGAGCGGGACCTGTAATTCCCTGCGCGTGCGGGAAGTCTACCCGCTTGTCGCGTGTGGGGCATACTCTGCTGAAGAGGTTTGCGTAACAATTCTGAGTTTCATTGCTGGTGGATGGCGGAGTGCAGCGGTGGAAGTCCCCTTGATGAAGGCTTTATGCAGGCGCTGGGGTTTACGGCACAACAGGGCGGCTGGAGAAGTGTCAAATCGTCAAGTTTAACTTCAAAAGTGATATTGCTGATGCGCTACGGGTCTTTATCAGGCGCAATGTGTGTTGCATGTCTACTGATTTCTTTGGATCTGTAGGCCGGATAAGGCGTTTTAATGCCCCACATCCGGCATGAAGCGGACTAGTACTCGATATTAGCAATATTTGCGGCAACCCAAAATTTCGCTTTAATTACCGTAATTTACCTCATCGGTCGCCGTGCTGTTGGCGTGCCAGTCAACCGCTAGAAACTCAATCCAGCTTTTCAGAGGATCGCCTTTTCTCATCCCAGGTCAGCGGTCCCATTACGGTATCCACGCGAGTTCGGTTTTCAGGTATTTGGCGATTTCAGCCGATCGTCATCAAATTTCAGGCCCGCCTGCAAAGATTGCAGCGCGGCGTCAGGTGGTCCAAACGAATCGCGCCACTTGGGTCCTGTTTTACGCTTTGACTGCGTCAACAATCGGGTTTGTTCGCTCGAACCTGCTAACTGCTTAGTTCTTCTATTGGTCACCAGCAGCCCTTCCGCTGATTTGCCCGCAATGTTAGACAGCGAAACGTTGATACACCTTCGCCTCCATAAACTGAGTTTCAGCCCTGCCGCGCGTGCCTGACCGCAGGATTTGCCCCATTTCCGGGTAACCGCCGTGTAGTAAACGAATTACGATATTCTCTTTTCTAAGACCGCGCCACCCGGTGTTGAATCTTTTCCCCGGCCCATCTGCCATCAAAGAAAATACGTTTGCAATTGCCTTTCTTCAGGCCATGTCCTGCAGGCCTCGCGCCAGACCTTCGCCGTATTGCTGTTTGGGCTGAACGTCAGCAATACGTGCAGGTTTCACTTTCTCAAGAATATATTTCGCCGCCGTCAGGCCCCTGGTTACGAGTCCAGGCCGGTGGGTCGCGTACGTACCGGATAGCCACGGGCGGTCAGCTCCGCTGAGGATTGCCGCTGGCGTAAGCTTAAAATCGCCTTCGTGTCTTCGTAGATGTCAGACGCAGGCTTAGTTGATGAAGAACAGAGGTACCAATCACATATTTAAATTGCCATTTATTTAACGACTTTGTTTCACCGCGCAACACGCCTGTTTCGGTCAGGCATCTACAGATAATTTAAGGAACTTGCAGTTTGTTGCCTTTAATGCCGCCTTTAGCGTTGATATCACAACCGCTTATGCGCCGGTAACTCCTGGTCACCGTACTGCGCAACCGGGTGGAAATGGACAATTGCCCCCAAGAACGCGACTTAATATCTTCTGCCAGCCATATTGCTGAATGCCAGCGCGATACATCCTGCCAGTAAACGCGCTTTACCCTTTATGTTCATCCTGGAACCCCATTCTTCTGGTTATTAATTTGTTGTGATGTTGTTGCCATCAATATTTATTTTCGTTTTATGCATGACTACCCGTGCTTTTTAGCAGCATACTTGGCCCAAACATACCGATTTTATGATATTGAAATAGCTATTTGACAGTGTCTATTAACAATCTGCGTGGGGATCAGTTTGCCGGAGGAACTTAATTATTACAGAGGCCCAAAACAAAACCCCGGCCACGCCATCCAGGGTTCTCTGCTTAAGGTAGCGGAAACTTAAGCTTCAATGGCATCAAGACCGCAATTTTCATACCGCGTTTCTTTTGCTCCAGCTGCGTACACGCTCAGCGGAAACGCTTAAAGGTCAGCGGTTCCTCTGCAAACGTGTACTGTTGTCTTCATTTAGCCAGCGCGACTGATGTCATCGGTGGCCGTTGCGTTCGGGATTCCATCTAGTCACATCGCGTCGGTCAGACGGTTTGCTCGCCTGCTCTTCCCAGTTATCATCTTCAATTGGCCGTTGGCAAAGTTAGCTATCGATTGTCATCCTTGGCAGATAGAGCACCGGGAGCCATCGGCTCGTTGAGGAAATCGTGTCGTCGGAAGACAGAGGTCAAAGGTCATGTCTCTGTGCCCGCCATACGTGAATTCCATCAACGATTGTCTTTGCTGGTTACACAGCAGTTCACGGGCCACCATTTCGACTTCATCCTGGTTAAACCAGCCCAGACCGCTGCTTGGTTTACGCAGATTGAAGAAACCAAGTTTGCGCTTGCGCTTTGGTGGTCGCAGGAACTGTTTGTACCGGAGTACTAAGTCCGCAGAACGTATTCGTGGGATCTCTGCTTTGATCACCAGTGAACGGCGAAGGAGACCATCGCACAATTATTCTTCTAGGTTGAAACGGCGCACTGCTTTCATCAGGCCGATGTTACCTTCCTGAATCAAATCGCCTGTGGCAGGCCAGCCCGCATAATTACGAGCATATGAACAACAAACCGCAGGTGAGACAGGCTGCAGCGTTTTAGCTGCTTTTCCGGGCACTGCCCGGTAATGCATATTTTAAGCCATGCCCCGCTCTCCGTCAGCCGACAACATCATACGCGTTGTCGCTGCCCGATGGGAATCCCAGGTTGCCAACTGGCTAAAGCAAACTTGCATATTTGTCAGTCATTCAAATCCTCACGATATCTTCTAGGGCCTGCCTGTCGCAACAAAGCTTGCCAGGATCAAGAGCGAAAGGTTATCATATTCAACTGTTTTATCAGACCAATCTGTTGTATCCACAAGTTCAATTCACCGGATGTGAAATAAATTACGCACAAAATGTGACATAGAGATGAAATACCGGGAGACTGAGGGTCTCTTCCCTGCTACGAACCCAACTTGCAGGGAAAGAGAGTAACACGCTTTATTATTCAGGCTAACCTAGTAAATGTTGTACCGTGGCAGCCACGCTTCGAGCCCAGCCAATCATCGAGCATACCAGCAGCAATAGCAGGGCATTGCCTATCGAATACCGATAAGGCCCATATTGATATCAAACTAACTTCGTTTCCGAGAAAACCTGTGCCACACCTCTTCGCAACCGCCGATGACAATCGCAGCACCAGAATTTTCTGACAAATTAATGACAACAATTGCGCCAGAAATCCCAGCAGTGCGCCACCATACTAGAAAACGTAGAGCAGGATGAATCCATTGTAGAGTGCACCAATCAGTTTCTTGGACTTTAATGAGTCATAAGCGAGCAAAGATACTGGGACGGCACACTGTTACCGATGACGAGAACACGGCCGCCACCATCAAACCACCCACGTAAGCCGAAACGCGCCGACCAGCCCGGTCAAACGCCGCCAGACGGGCAAAACCAGCTGTCATCATCCGCACTTCGTCAATGCCATTTATCAATCTGCGTGATACGTGATCACGCATGGTCAGTGCCAGTAATTCCCTATGTCCCCTGGGAAACCCAGATTTCGGGATCAGAATCGCCATAATGCCGGAATAGCGGGTTTTCTTCCAGCATCTACAGCGCACCACCAAAACCAGACTCAGTTACCGAGTACGCGATGTTAGCGTGTCTTCACGAGAAGATAAGTTCACTTTCTGACTCCGCTTGCTCGGCCTGCAACTGTGCCATCAACAGCCACGCAGCAATCCTTCACGGATGTTTTGCAGATAAACAGTGATATTTCGAACGATAATACTGCCTTCGCCTGGGTTAAACGTTTTACACCATAACAGACGCTGGGCGGCACCGGTCAGAGAACCCGATAACCATCACCGTTAAAACGTCTTAGCGAACGGTTTGCTTTCAGATTAATCCGCAATGCGCCGTGGAAGGCACCACGCGCAGCTGTTTCGGTTGAAAACAGCTTTGGTTTGCGATTTACCGGTTTGGCGAGGATAACAATTTCTGGCGCGTGTTTTGTAGTGCGTCAGAACCTCAGCCTCCGCTTCTAACAGCCGATTTACGGGAACACCGCGATCAAGACGCGAGCCAAATTGCCGAAAATATAATTGACTTGCATATCGCGCTTATTCATCTAGCACGCCTCCATGCAAGTGACCATCGCTCAGGGTGAGCATGCGATAGGAACGCCGGGAGGTTACGATTGATCATTGTGCGTTGCCATCAATACGGTTACCCAACGCGGTTAAACTCTTCCAAACAGACGTAAAATGCCTTTCTCGACAAGTCCTGAGGTTACCAGTCGGTTCTGTCCGCCAGCAGTAACCCCTTAGTTTCATCCACCGCGCGGGTGGCAATTGCCAACACGCTGTTGTTGGCACCGCCCGAAAGCTGAATAGGGAAGTTGGTTCTCGCTTTGTCCAGCCCGACTTTATCCAGCGCCGCCGACACCCGGCGACCCAATGTCACCGCTGGCAGGCGATAATCAAGCGGCGTAAAAATTGCCACTTAGACAGTAATGTTGGATAATAGATGATCCTGGAAAACCGCTTGCCAATGGGCATAGAAACGAACTTCACGGTTTTCGACCGCGAGCGGTGATGTCATATGAGGACAACCAGATTTTCCCGGCGCTGGGCCGCTCAATCGTACAGGATCAGCTTCGCAGATTTTCTTATTTAGAATACGAATTCCAAAACGCCATCGCCGATGGGTGCATATGGAAATGGTAACGCCCTGCGCAGCGCCTGTACTCCCACCGAGATAATGTGCTGACATGTTCAAAGCGAATCATTGTTAATCCTCTCGGGCAAAATTGCCTCTATAAAGTCGTCCGCCTTAAACGGACGCAAATCCTCTAATACGTTTGCCGACACCAATGTAGCGGATAGGGATACCAAACTGGTCAGCCACCCAGAAAATTACCGACTTCGCTTTGCCGCTTTAAGTTTCGTCAGGCGCGTGGACTCATGTCATAAGCCAACGGCTTCATCGAACAGTGTTGCCTGCTTACCGCGATTCTGCCCGGTGCTGGCATCAATAATTACCAGCATAATTTCATGCGGCGCTTTCAACGTCGAGTTTCTTCATCACGCGGACGATTTTCTTCAACTCTTCTACATCAGGTGCGATTTGTTTCTGCAGGCGCAGTCCGGGGCCTGTAATGGCAATCAGGAAAGTCGATATTGACGCGCTATTTAGCTGCCTGAACCTAGTCGAAAGATAACAGAGGCGAATCTCCGGTATGCTGGGCAATCACCGGAATATTGTTGCGCTGACCCCAGATATGAAGCTGTTCAACGCAGCTTGCACGGAAGATGACCTGCCGCCAGCATCACCGATTTACCCTGCTGCTCAAACTGACGCGCCAGCTTACCAATCGTCGTGGTTTTCCCACACCGTTGAAGCCCACCATCAGCAGTAACCAAACGGCGCTTTGCCTTCAAATATTCAGCGGCTCATCGACTTTCGCCAGAATCTCGCCCATCTCTTCTTCATAGCAAGGCCATAGAGCTGCCTCGGGGTTACGCAACTATGCTGCGCGTACATTTCTGCCTCCGTCAGATTGGTAATTTTACGTGTGGTTTCCACACCCAATTAGGCAATCAAAACAAGCTTAGCTCTTCCAGCTCCTCAAAATACGACCCGGTAGCGTTACGATTTTACCGCGGAACAGGCTGATAAAATCCGAGAACCGAGATTTTCTTTGGTTTTAACAGGCTGCGTTTCAGGCGCGCGAAAATTAATTCTTTGTATTGGTTTTTCCTGCTCCTGAGCGATTTCTTCACCGGCTGCTCTTCTTCTGCCGGAGGAACAACAAGAACACCTCTTCTGCCGCTTCGGCAGCCAGCGGGTTTCCTATGTTCTCGTCGGTGATTTCTTCTTTAGCCGCTTCTTCTTCAGCCGCTATTCGACAATCTCTACGGTTTCGCTTCAGCCTGCCACTCTTCTGAATACGATTTGCTTCGGCGTTGACGTCTTCTAGCGGCAACGGCATTAGCCTCTATTTCTACGTTCAAGCGCTCCGATTTCTTCTACGACAAGCTCCCTGTTGCGTCAAAGGCTACATCTTCCGCTTCAGGCTTCGCTTTTCACTTTCAGCAACCTGTTCAGGTGACTTCTCCACAACGTCGGCAGGGACAAAGTTTCTTCGCTCGGCTTCAGTATGCGCTTGCGGCTGCTCTTCAACCGCTTGTTCAGAGGCCTTCACAGGCTCTATTGCGCCTGAACGATTTCTTCTACAACCGGTTGTTCATATTCTGATTCTGTCTCTTTTCCGGGGTCTGCTCTTTGACCAAGCCCAGCCAAGAAGGCTTTTCTTTTCACATACTGACTTTACAGCCTCCTATGTTGCTTTCATGGCACAGCGTCAAACGCTATGTACATAGCAGCTAAAATGATGAAATAGTCTATCACTTAACTTAATTCACATCAAGCTGCAATATGTTATCTGGCGGATTGAGCAATTTATCATGAAAATGGCAAATCATTCCGGACACAGCGGCCAAATCGCATTATTGGCGGGCATGGCGGGGCTTACTCCTCCCGGTTCCTGTCACTAAGGTCTCTGCCCCACCAATGACTCGGTACGGGGCAACGGTTGTTTAACTGGCTGAGCCGGTTGATGTTGACTCGCCCAATGTCTGGATTGCTTCGCCGGGAGCGGCTCGAGGGTGGCTGAAGGGTTTGGGCGCTACATTGCTCGCGGGGGCAACGGTTGACTTGAGATGGATCGCGTTGGCCATCGAAGTTAATTAAGAATCTGGCGACACTAAAATTAAGAGAGGCAATGCGAAGAGCGTGGTGAACAGCAACGCGATGTCCAATTCCTGGGGGCAAAGGTACACCGCATAATACTGTGTTTGTCGATCACCGTTCGCCTTGGCTTTAGAGACGATAAATTTACTGAGAAGATAGACCGTAGCTGGCTGACGAAGCCCTGTAAGTTGTATGTCGAAAGCGAAGTCGAAAACGGTCTGCCACTGTTCGAGCAAACTGGTCTATTACATCGCAAAATTAGGGTCAGGTAGGCTTATCGGCTGTATCAACGCGACAGCACAAGGAGAAAGTGATGCTGTCGTGATAATATTATGCTTTTGTTAATGCTCTGCGTTTGGGGATTTTAATCCTCAACCTGGGTCGCATCCTTCCCCACGCCCGCTGAATATCTTCTAGTTAACGTGGCGCTGATTTTAAGTTTGGTTTATGG";
    char* text = "bannna";
    char* pattern = "ana";
//    char *text = "Ovo je random dugi string cisto da isprobam kako radi kada imam nesto duze sto mozda malo duze treba parsirati. Parsiranje je jako kul ali ne radi najbolje.";
//    char *pattern = "randikdso";
//    char *text = "banana";
//    char *pattern = "ana";
    int textLength = strlen(text);
    int patternLength = strlen(pattern);
    int k = 1;

//    int isa[] = { 5, 2, 7, 3, 8, 4, 9, 1, 6, 0 };
//    char* sa[] = { "a", "ana", "anana#ana", "ana#ana","a#ana", "banana#ana", "na", "nana#ana", "na#ana", "#ana" };
    int isa[] = { 4, 2, 8, 7, 6, 3, 9, 1, 5, 0 };
    char* sa[] = { "a", "ana", "annna#ana", "a#ana", "bannna#ana", "na", "na#ana", "nna#ana", "nnna#ana", "#ana" };

    NaiveMismatcher mismatcher(text, textLength, pattern, patternLength, k);
    clock_t begin = clock();
    int* mismatches = mismatcher.findMismatches();
    clock_t end = clock();
    double elapsed_secs1 = double(end - begin) / CLOCKS_PER_SEC;

    for (int i = 0; i < textLength - patternLength + 1; i++) {
        if(0 <= mismatches[i] && mismatches[i] <= k) {
            cout << i << ":" << mismatches[i] << endl;
        }
    }
    KangarooMismatcher kangarooMismatcher(sa, isa, text, textLength, pattern, patternLength, k);
    begin = clock();
    int* kangarooMismatches = kangarooMismatcher.findMismatches();
    end = clock();
    double elapsed_secs2 = double(end - begin) / CLOCKS_PER_SEC;

    for (int i = 0; i < textLength - patternLength + 1; i++) {
        if(0 <= kangarooMismatches[i] && kangarooMismatches[i] <= k) {
            cout << i << ":" << kangarooMismatches[i] << endl;
        }
    }
    cout << endl << "Time:" << endl;
    cout << elapsed_secs1 << endl;
    cout << elapsed_secs2 << endl;
//    cout << kangarooMismatcher.rmqTime << endl;


    return 0;
}


